### ISSUE TITLE
"jsonwebtoken" should be required.

### ISSUE THREAD

**Issue by moka-a** [wan2land/graphity#246]
<img width="923" alt="Screen Shot 2021-05-22 at 8 13 50 PM" src="https://user-images.githubusercontent.com/7301713/119224618-3d8bc700-bb3a-11eb-8992-f45931a05cb5.png">

**Comment by wan2land** [comment]
This is an unnecessary package for people who don't use authentication, so I didn't add it to the dependency.

It will be added to peerDependency.
